version: '3.7'
services: 
  web:
    build: "./docker/web"
    container_name: "centos"
    ports:
      - 80:80
      - 6001:6001
    volumes:
      - ".html/:/var/www/html"
      - "./:/docker"
    privileged: true

  database:
    build: "./docker/database"
    container_name: "database"
    ports:
      - 3306:3306
      - "2222:22"

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # command: --default-authentication-plugin=mysql_native_password
    privileged: true
