version: '3.7'
services: 
  web:
    build: "./docker/web"
    container_name: "centos"
    ports:
      - 80:80
      - 6001:6001
    volumes:
      - ".html/:/var/www/html"
      - "./:/docker"
    privileged: true
  # database:
